# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Wang
email: andrewyw@andrewyw.me
description: > # this means to ignore newlines until "baseurl:"
  Computer Science/Music Student at Rutgers University - New Brunswick
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andrewyw.me" # the base hostname & protocol for your site
github_username:  AndrewYW
linkedin_username:
twitter_username:
google_plus_username:
facebook_username:
# Build settings
markdown: kramdown
